travis:
  secure:
    BINSTAR_TOKEN: PZ+fK730tFxDVxLTB0cXzKb2mV3AzPJGy20qVR8RjNWflTSQYxpQeUpM5OvY7MDxRSPXiRtMcb44jVjXqU7a2EuEJIVtO3HDNss6wf9uAMVgvuGYxOgGFfszRLYeW8uTreL456XwQ6kdE0M6FvaceU80pgXYkdHo/8NQTjY4kK5HiluQ3LL/JaISlqzI8MwDLf6uOJIywTQndWA0rOjkTKx5x7WhmCOd696JVjnooru8M5BG3LoUWujs7UFa2om0iCclVu4E1rQP0zfyTzns/TGkrkBrfK+KoBrISyFgeKnPHpA1DKTkzcd5ZanwKQtM14YumQfZABNW/bT0l/Sl83nVEuen6OL7fSWM6QmC3q18AKuNHNgnyOFu3o+MM3CFPi271CVZHEtS09LmiGSpz7tKdmTclR9a1vJQYP1hQFci5hMuasB8BPm06o2GO2ZzZ8e2RD3ewPX8jDTqHoN7RkMY2SHZHpYd5clUYNpMIs1+jq95EYysunSdpXcunl8KktIgbmvpXziGmREnUWY8/2fiSye9k8DoKANFrYN8v5cjREhDH+qVtMTzIsOdkq59jYdT/Kb5bTi/DnbQJ+sblCfy1WYcCwkiLg7poqz4CoAzuq+wHBZMe+FEE312nxLXkQ1prpQ1fTcDxfn3uMfEpGGl4YOJjU9K+nrdI+7Sr/I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
