travis:
  secure:
    BINSTAR_TOKEN: zJl+Nf6Q0eJRXGMndhbUxHXlgmrx69xdJDZvCpBLyv5QT3+wX+YLXS5gK30Ll/IcClhtr/Dzz/y6lkWGNG0nak3SnZ+RGo0QG+2cq7FyxcAoXkFcq92tae/Wt3H+mjuubFw700KoYkh6StfWBr9Ss+tckmbDsGeug72mpcyw01hOeBvkvoTnn06Pi727CGxRB1r4YfiRLWfj8kE5nurYYv6QYcJpgdg4IjebvdNwa/UBqdIFtwhT/pUC7opEtB3h62igGpIkEuPEbsWQ6MzIOCY/lrRloe0Vqo8R/CfKEIuC7KMmxTaMAhKHscPEuVQsQw2M+2vsSX66e9+8ZcCluwM6WnXwNF1ZgyKJnsdg8x1+2QJltMmjGVNQPGRo3epaw5gb6Am52a+NLgJDhmwXpLOf/N8vByTh3OiPlkxI3nR6yI3yqcUtha0dfhTKVXR+nKrLJ5dwK7b15udng1UcETKtEGNXKTcXqsxog+LPwJ2EJ3LSzK9TjM3Nc9hh/zRYBAKm3PzE5vm/c38J4dcSO9J9lnqaxcRxCbI3oZDcs6+f35mLThTLrGO5zJSDB4t/CLEAGU2kfbOUiwhQQFqdjK1men98oEaGym5Y2Yswbamx5sYCDcrmlKpuWhqlDRGcIQZ5ZFjafwkx6+g8rjQ9T6taBkIrmxNgfQ0t14ICEVc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
