appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure, win: azure}
travis:
  secure: {BINSTAR_TOKEN: YCuv5/T/BetIabNQi3ee4fopoeeLiW7RA3O9oXRMq2wudhkW8lw8rdRP0hFF/nr7dfWV8FOZPJihq2yhkmdLMuwRPjl2jPMscFJWcr0KOu2eSQ592lx6gcYG/w+mDwNCeNRE3CI6Wk3dymPtERLrc1/KykRyL9e7ujht876ZZ9iAxIQXKVf5VH7fDILW0rXwS5Y3fvtGoDsHGrTfGn6CSKJh37vyN0qopr28vPAhQHuDSAp/nUEZz00gwdu1pA7gCkf7OnSi33Mk0MA0Vx+eFaJLC/LuYEb3zzcF3W+Q9J5CJtMLgz1qT9zJqbuA0DnNz7S+hYhpkxhrwyMBT493v5q8rz/sunnanrpH8/TGODja5JOXomfb3/hXq9CnqH+11qwlnAsbN45s++ubENyWNkf6207biSAKbbnFQngCL/oNh62v9wYvPjwaMno8MRVLwKYic8gUzx7si/zBj5+wXYC5xnIil/z8ScF3RodUHt3JbFJYMRvuuxdBtPAxoEzAKjFl1E8R61mwUAwQhk8EWBIL/NFEl3DxZDBEyjfuY2HTWhr3TST/8LOMuU9FgWdZfxgu2LCe5IPynMieEMVzRItCPINph75N7I9mHCTFDsBi2VuO4L3x6f3xLCUVz0Trk9GanHU9vt4b2W8D85q3+w0/8bkUwO8BCjdKuEQ6I2w=}
conda_forge_output_validation: true
